### ISSUE TITLE
Issue with /lib/pkginfo.js for finding package.json

### ISSUE THREAD

**Issue by owenashurst** [indexzero/node-pkginfo#27]
I've experienced a rather serious issue in which when attempting to debug in visual studio code a solution that uses pkginfo, I would get an error for pkginfo that the package.json file cannot be found inside \lib/package.json.

I believe on line 104 of pkgingfo.js file in /lib is wrong and should actually be looking 2 directories back in the root folder.

e.g. 

wrong line: contents = require(dir + '/package.json');
should be: contents = require(dir + '../../package.json');

**Comment by stvngrsh** [comment]
I'm having the same issue. Cannot debug a project using VSCode because one of my packages uses pkginfo as a subdependency. 

I get the following error: 
`Exception has occurred: Error
Error: Cannot find module '/Users/sgresh/vms/vdem/vdem/data-access/node_modules/pkginfo/lib/package.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Function.pkginfo.find (/Users/sgresh/vms/vdem/vdem/data-access/node_modules/pkginfo/lib/pkginfo.js:104:16)
    at Function.pkginfo.read (/Users/sgresh/vms/vdem/vdem/data-access/node_modules/pkginfo/lib/pkginfo.js:122:22)
    at module.exports (/Users/sgresh/vms/vdem/vdem/data-access/node_modules/pkginfo/lib/pkginfo.js:68:21)
    at Object.<anonymous> (/Users/sgresh/vms/vdem/vdem/data-access/node_modules/pkginfo/lib/pkginfo.js:129:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)`

**Comment by stvngrsh** [comment]
I'm having the same issue. Cannot debug a project using VSCode because one of my packages uses pkginfo as a subdependency. This may also be just an issue with VSCode or our debug config, because I've had this happen with another package, where the module importer looks in the lib/build folder for package.json. 

I get the following error:

```
Exception has occurred: Error
Error: Cannot find module '[PROJECT PATH]/node_modules/pkginfo/lib/package.json'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Function.pkginfo.find ([PROJECT PATH]/node_modules/pkginfo/lib/pkginfo.js:104:16)
    at Function.pkginfo.read ([PROJECT PATH]/node_modules/pkginfo/lib/pkginfo.js:122:22)
    at module.exports ([PROJECT PATH]/node_modules/pkginfo/lib/pkginfo.js:68:21)
    at Object.<anonymous> ([PROJECT PATH]/node_modules/pkginfo/lib/pkginfo.js:129:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
```

**Comment by michelle-morin** [comment]
Is there any resolution for this? I am having the same issue, more than two years later.
