### ISSUE TITLE
Test failures in Windows

### ISSUE THREAD

**Issue by mcandre** [indexzero/node-pkginfo#8]
Looks like path names are giving pkginfo trouble in Windows.

Trace:

```
$ npm test

> pkginfo@0.3.0 test c:\Documents and Settings\apenneba\Desktop\src\node-pkginfo
> vows test/*-test.js --spec


  ♢ pkginfo

  When using the pkginfo module and passed a single string argument
    ✗ should expose that property correctly
        » expected null, got {
      stack: "Error: Command failed: \015\nmodule.js:340\015\n    throw err;\015\n
    ^\015\nError: Cannot find module 'c:\\Documents'\015\n    at Function.Module._resolveFilename (module.js:338:15)\015\n    at Function.Module._load (module.js:280:25)\015\n
   at Function.Module.runMain (module.js:497:10)\015\n    at startup (node.js:119:16)\015\n    at node.js:901:3\015\n\n    at ChildProcess.exithandler (child_process.js:634:15)\n    at ChildProcess.EventEmitter.emit (events.js:98:17)\n    at ChildProcess.options.Emitter.emit (c:\\Documents and Settings\\apenneba\\Desktop\\src\\node-pkginfo\\node_modules\\vows\\lib\\vows.js:237:24)\n    at maybeClose (child_process.js:732:16)\n    at Process.ChildProcess._handle.onexit (child_process.js:799:5)",
      arguments: undefined,
      type: undefined,
      message: "Command failed: \015\nmodule.js:340\015\n    throw err;\015\n          ^\015\nError: Cannot find module 'c:\\Documents'\015\n    at Function.Module._resolveFilename (module.js:338:15)\015\n    at Function.Module._load (module.js:280:25)\015\n    at Function.Module.runMain (module.js:497:10)\015\n    at startup (node.js:119:16)\015\n
  at node.js:901:3\015\n",
      killed: false,
      code: 8,
      signal: null
  } // module.js:338
  When using the pkginfo module and passed an object argument
    ✗ should expose that property correctly
        » expected null, got . // pkginfo-test.js:43
  When using the pkginfo module and passed multiple string arguments
    ✗ should expose that property correctly
        » expected null, got . // pkginfo-test.js:43
  When using the pkginfo module and read from a specified directory
    ✗ should expose that property correctly
        » expected null, got . // pkginfo-test.js:43
  When using the pkginfo module and passed an array argument
    ✗ should expose that property correctly
        » expected null, got . // pkginfo-test.js:43
  When using the pkginfo module and passed no arguments
    ✗ should expose that property correctly
        » expected null, got . // pkginfo-test.js:43

✗ Broken » 6 broken (4.377s)
```

I tried `npm test` in Command Prompt as well as Git Bash, and get the same failing tests.

System:

```
$ specs node git os
Specs:

specs 0.4
https://github.com/mcandre/specs#readme

npm --version
1.2.17

node --version
v0.10.3

git --version
git version 1.8.0.msysgit.0

systeminfo | findstr /B /C:"OS Name" /C:"OS Version"
OS Name:                   Microsoft Windows XP Professional
OS Version:                5.1.2600 Service Pack 3 Build 2600
```

**Comment by indexzero** [comment]
Closing due to age.
